/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drive.mate.learner;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author smbha
 */
public class SelectLanguage extends javax.swing.JFrame {

    public static String selectedLanguage;

    /**
     * Creates new form SelectLanguage
     */
    public SelectLanguage() {
        initComponents();

        this.setExtendedState(this.MAXIMIZED_BOTH);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                AlertMessages.conformExit(); // Call the method from AlertMessages class
            }
        });

       // Image icon = new ImageIcon(this.getClass().getResource("/res/logo.png")).getImage();
        //this.setIconImage(icon);

        ImageIcon logoIcon = new ImageIcon(this.getClass().getResource("/res/logo.png"));
        ImageIcon logoIcon2 = new ImageIcon(this.getClass().getResource("/res/whitenlogo.png"));

        Image scaledImage = logoIcon.getImage().getScaledInstance(logolbl.getWidth(), logolbl.getHeight(), Image.SCALE_SMOOTH);
         Image scaledImage2 = logoIcon2.getImage().getScaledInstance(lbl2.getWidth(), lbl2.getHeight(), Image.SCALE_SMOOTH);
        logoIcon = new ImageIcon(scaledImage);
        logoIcon2 =  new ImageIcon(scaledImage2);

        logolbl.setIcon(logoIcon);
        //lbl2.setIcon(logoIcon2);

        // Set default background color
        Color defaultColor = Color.decode("#FFFF00");
        Color hoverColor = Color.decode("#D8D822");

        // Apply default background color
        englishbtn.setBackground(defaultColor);
        sinhalabtn.setBackground(defaultColor);
        tamilbtn.setBackground(defaultColor);

        // Add hover effect
        addHoverEffect(englishbtn, defaultColor, hoverColor);
        addHoverEffect(sinhalabtn, defaultColor, hoverColor);
        addHoverEffect(tamilbtn, defaultColor, hoverColor);

        // Add action listeners to the buttons
        englishbtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                selectedLanguage = "English";
                openUserLoginScreen(selectedLanguage);
            }
        });

        sinhalabtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                selectedLanguage = "Sinhala";
                openUserLoginScreen(selectedLanguage);
            }
        });

        tamilbtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                selectedLanguage = "Tamil";
                openUserLoginScreen(selectedLanguage);
            }
        });

    }

    private void addHoverEffect(JButton button, Color defaultColor, Color hoverColor) {
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(hoverColor);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(defaultColor);
            }
        });
    }

    private void openUserLoginScreen(String language) {
        // Create an instance of UserLoginScreen
        UserLoginScreen loginScreen = new UserLoginScreen(language);
        // Make UserLoginScreen visible
        loginScreen.setVisible(true);
        // Close SelectLanguage frame
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tamilbtn = new javax.swing.JButton();
        englishbtn = new javax.swing.JButton();
        sinhalabtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 31, 31));

        tamilbtn.setBackground(new java.awt.Color(255, 255, 0));
        tamilbtn.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tamilbtn.setForeground(new java.awt.Color(31, 31, 31));
        tamilbtn.setText("தமிழ்");
        tamilbtn.setBorder(null);
        tamilbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tamilbtn.setPreferredSize(new java.awt.Dimension(200, 60));

        englishbtn.setBackground(new java.awt.Color(255, 255, 0));
        englishbtn.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        englishbtn.setForeground(new java.awt.Color(31, 31, 31));
        englishbtn.setText("English");
        englishbtn.setBorder(null);
        englishbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        englishbtn.setPreferredSize(new java.awt.Dimension(200, 60));

        sinhalabtn.setBackground(new java.awt.Color(255, 255, 0));
        sinhalabtn.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        sinhalabtn.setForeground(new java.awt.Color(31, 31, 31));
        sinhalabtn.setText("සිංහල");
        sinhalabtn.setBorder(null);
        sinhalabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sinhalabtn.setPreferredSize(new java.awt.Dimension(200, 60));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT YOUR LANGUAGE");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ඔබේ භාෂාව තෝරන්න");

        logolbl.setPreferredSize(new java.awt.Dimension(150, 150));

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 0));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("WELCOME TO DRIVEMATE");
        lbl2.setToolTipText("");
        lbl2.setPreferredSize(new java.awt.Dimension(300, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(englishbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(sinhalabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tamilbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(logolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamilbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sinhalabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(englishbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectLanguage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton englishbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel logolbl;
    private javax.swing.JButton sinhalabtn;
    private javax.swing.JButton tamilbtn;
    // End of variables declaration//GEN-END:variables
}
